# Generated by Django 4.0.4 on 2022-06-16 19:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=70)),
                ('anno_uscita', models.IntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2022)])),
                ('trama', models.TextField(max_length=800, null=True)),
            ],
            options={
                'verbose_name_plural': 'Film',
            },
        ),
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Generi',
            },
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='/', max_length=50)),
                ('password', models.CharField(default='/', max_length=25)),
                ('nome', models.CharField(default='/', max_length=50)),
                ('cognome', models.CharField(default='/', max_length=50)),
                ('film_guardati', models.ManyToManyField(default=None, to='streamify.film')),
            ],
            options={
                'verbose_name_plural': 'Utenti',
            },
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commento_scritto', models.CharField(default=None, max_length=500)),
                ('film', models.ForeignKey(default='/', on_delete=django.db.models.deletion.CASCADE, to='streamify.film')),
                ('utente', models.ForeignKey(default='/', on_delete=django.db.models.deletion.CASCADE, to='streamify.utente')),
            ],
            options={
                'verbose_name_plural': 'Recensioni',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='generi',
            field=models.ManyToManyField(to='streamify.genere'),
        ),
        migrations.AddConstraint(
            model_name='recensione',
            constraint=models.UniqueConstraint(fields=('utente', 'film'), name='unique_constraint_utente_film'),
        ),
    ]
