# Generated by Django 4.0.4 on 2022-05-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Generi',
            },
        ),
        migrations.RemoveField(
            model_name='utente',
            name='id',
        ),
        migrations.AlterField(
            model_name='utente',
            name='username',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=70)),
                ('anno_uscita', models.IntegerField()),
                ('generi', models.ManyToManyField(to='streamify.genere')),
            ],
            options={
                'verbose_name_plural': 'Film',
            },
        ),
    ]
