# Generated by Django 4.0.4 on 2022-06-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamify', '0002_remove_film_trama'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='trama',
            field=models.TextField(max_length=800, null=True),
        ),
    ]
