# Generated by Django 4.0.4 on 2022-05-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamify', '0003_film_valutazione_alter_film_anno_uscita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='valutazione',
            field=models.IntegerField(default=None),
        ),
    ]
