# Generated by Django 4.0.4 on 2022-05-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamify', '0004_alter_film_valutazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='film_guardati',
            field=models.ManyToManyField(default=None, to='streamify.film'),
        ),
    ]
