# Generated by Django 4.0.4 on 2022-07-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamify', '0004_utente_film_preferiti_alter_utente_film_guardati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='email',
            field=models.EmailField(default='/', max_length=50, unique=True),
        ),
    ]
