# Generated by Django 4.0.4 on 2022-05-17 18:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamify', '0005_utente_film_guardati'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamify.film')),
            ],
            options={
                'verbose_name_plural': 'Recensioni',
            },
        ),
        migrations.AddField(
            model_name='utente',
            name='recensioni',
            field=models.ManyToManyField(default=None, to='streamify.recensione'),
        ),
    ]
