# Generated by Django 4.0.4 on 2022-07-02 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamify', '0005_alter_utente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 10, 26, 44, 885793)),
        ),
        migrations.AddField(
            model_name='utente',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utente',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utente',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utente',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
