# Generated by Django 4.0.4 on 2022-07-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamify', '0006_utente_date_joined_utente_is_active_utente_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utente',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='utente',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
