# Generated by Django 4.0.4 on 2022-05-18 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamify', '0006_recensione_utente_recensioni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='valutazione',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='recensioni',
        ),
        migrations.AddField(
            model_name='recensione',
            name='commento_scritto',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='recensione',
            name='utente',
            field=models.ForeignKey(default='/', on_delete=django.db.models.deletion.CASCADE, to='streamify.utente'),
        ),
        migrations.AddField(
            model_name='utente',
            name='cognome',
            field=models.CharField(default='/', max_length=50),
        ),
        migrations.AddField(
            model_name='utente',
            name='nome',
            field=models.CharField(default='/', max_length=50),
        ),
        migrations.AlterField(
            model_name='film',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recensione',
            name='film',
            field=models.ForeignKey(default='/', on_delete=django.db.models.deletion.CASCADE, to='streamify.film'),
        ),
        migrations.AlterField(
            model_name='utente',
            name='email',
            field=models.EmailField(default='/', max_length=50),
        ),
        migrations.AlterField(
            model_name='utente',
            name='password',
            field=models.CharField(default='/', max_length=25),
        ),
    ]
