# Generated by Django 4.0.4 on 2022-05-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamify', '0007_remove_film_valutazione_remove_utente_recensioni_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recensione',
            constraint=models.UniqueConstraint(fields=('utente', 'film'), name='unique_constraint_utente_film'),
        ),
    ]
