# Generated by Django 4.0.4 on 2022-07-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamify', '0008_utente_is_staff_utente_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='password',
            field=models.CharField(default='/', max_length=200),
        ),
    ]
