# Generated by Django 4.0.4 on 2022-05-18 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamify', '0008_recensione_unique_constraint_utente_film'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recensione',
            name='unique_constraint_utente_film',
        ),
        migrations.AlterUniqueTogether(
            name='recensione',
            unique_together={('utente', 'film')},
        ),
    ]
