# Generated by Django 4.0.4 on 2022-05-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamify', '0009_remove_recensione_unique_constraint_utente_film_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recensione',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='recensione',
            constraint=models.UniqueConstraint(fields=('utente', 'film'), name='unique_constraint_utente_film'),
        ),
    ]
